### ISSUE TITLE
Multiple database monitoring with one daemon

### ISSUE THREAD

**Issue by jglapa** [GoBoundless/newrelic_postgres_plugin#21]
Is it possible to monitor multiple databases with one pg_monitor process?
'agents' are written in plural so I thought it's possible to add multiple db configs.
It seems that only the last one gets monitored.

``` yaml
# Agent Configuration:
#
agents:
  # this is where configuration for agents belongs
  postgres:
    host: 'db.foo.bar'
    port: 5432
    user: 'user'
    password: 'pass'
    dbname: 'db_name'
    sslmode: 'require' # (disable|allow|prefer|require)
  postgres:
    host: 'db1.foo.bar'
    port: 5432
    user: 'use1r'
    password: 'pass1'
    dbname: 'db_name2'
    sslmode: 'require' # (disable|allow|prefer|require)
  ...
```
